/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_drizzle_adler_Adler32 */

#ifndef _Included_org_drizzle_adler_Adler32
#define _Included_org_drizzle_adler_Adler32
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_drizzle_adler_Adler32
 * Method:    checksum
 * Signature: (Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_drizzle_adler_Adler32_checksum
  (JNIEnv *, jobject, jobject, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
